.PHONY: all clean build package

all: build package

build:
	@echo "Running build script..."
	./build-package.sh

package:
	@echo "Packaging done in build-and-package.sh"

clean:
	rm -rf build/*
	@echo "Cleaned build directory."
